zetton_inference:
  mot_tracker:
    tracker:
      track_fail_timeout_tick: 5
      bbox_overlap_ratio: 0.6
      detector_update_timeout_tick: 30
      detector_bbox_padding: 10
      reid_match_threshold: 3.0
      reid_match_bbox_dis: 80
      reid_match_bbox_size_diff: 80
      stop_opt_timeout: 2

    local_database:
      height_width_ratio_min: 0.85
      height_width_ratio_max: 4.0
      record_interval: 0.1
      feature_smooth_ratio: 0.7

    kalman_filter:
      q_xy: 100
      q_wh: 25
      p_xy_pos: 100
      p_xy_dp: 10000
      p_wh_size: 25
      p_wh_ds: 25
      r_theta: 0.08 # 0.02 rad 1 degree
      r_f: 0.04
      r_tx: 4
      r_ty: 4
      residual_threshold: 16

    optical_flow:
      min_keypoints_to_track: 10
      keypoints_num_factor_area: 8000
      corner_detector_max_num: 1000
      corner_detector_quality_level: 0.06
      corner_detector_min_distance: 1
      corner_detector_block_size: 3
      corner_detector_use_harris: false
      corner_detector_k: 0.04
      min_keypoints_to_cal_H_mat: 10
      min_keypoints_for_motion_estimation: 50
      min_pixel_dis_square_for_scene_point: 2
      use_resize: true
      resize_factor: 2
